### ISSUE TITLE
Main aircraft model

### ISSUE THREAD

**Issue by colingeniet** [NikolaiVChr/flightgear-viggen-masters#22]
There are a few mismatches between the ac3d and blender main aircraft files, I am trying to merge them before making additional changes:
- On the blender side, I found a fix for the normals problem introduced by l0k1 multivariant PR (using [data transfer modifiers](https://docs.blender.org/manual/en/2.79/modeling/modifiers/modify/data_transfer.html)), so I think everything is fine.
- On the ac3d side, most changes are to the materials, and are easy to merge by hand. However this commit is problematic: https://github.com/NikolaiVChr/flightgear-saab-ja-37-viggen/commit/36907ac060d89293014d8d9adac43a8c2f6c0223
I am not sure what it does. Would you know how to port it to the blender file ?

**Comment by NikolaiVChr** [comment]
Hehe, everything that has to do with the main models are delicate work, I am always very careful when doing that.

If you fixed the normals in blender thats not going help, because normals cannot be exported to AC3D, AC3D makes its normals only by if vertices are defined clockwise or counterclockwise.
The only way to fix them is to stitch the geometry back together. And pretty much have 1 model per variant he made.

That commit takes some faces that were defined as single-sided flat, and make them single-sided smooth. And some were double sided flat, those I made double sided smooth.

It is best to stick to 2.79 for this, cause 2.80 no longer have difference between single an double sided.

The commit is easy to do by text editor, so dont worry about it too much, its just for whole file:
0x0 to 0x10
0x20 to 0x30

**Comment by colingeniet** [comment]
Indeed, I was just now noticing that my magic fix did not work whatsoever for flightgear. I suppose I will do it the simple way in that case.

Thank you for the explanations on that commit, I will see if I can locate the offending faces in blender, to avoid having to do the text replacement every time.

**Comment by NikolaiVChr** [comment]
You can just find which object(s) the faces are in and make the whole object smooth with 1 click. Don't have to do it face by face. I don't think there should be any flat faces anywhere.

**Comment by NikolaiVChr** [comment]
If you are in doubt about which object should be set visible for which variant of the aircraft just ask.

**Comment by NikolaiVChr** [comment]
As for the materials, I dont even touch them in Blender, I always edit them by hand, so its the AC3D materials thats up-to-date.

I see you fixed the landing gear bay issue in this pull request also, I will merge.
